all:
  vars:
    control_plane_endpoint: 192.168.0.100
    load_balancer_ip_pool:
      - 192.168.0.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.0.10, mac: 'BC:24:11:5E:6D:4F', disk: sda, network_interface: ens18}
        metal1: {ansible_host: 192.168.0.9, mac: 'BC:24:11:B2:CE:03', disk: sda, network_interface: ens18}
        metal2: {ansible_host: 192.168.0.8, mac: 'BC:24:11:9D:F5:97', disk: sda, network_interface: ens18}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.0.11, mac: 'BC:24:11:94:8B:E3', disk: sda, network_interface: ens18}
